# ============================================================
# DIRECTIONAL / CONTRASTIVE LOCAL SCORE LOSS  (Error 3 fix)
#
# Problem with the absolute score loss:
#   L_score = MSE(ScoreNet(decode(x0_hat(target_prompt))), target_score)
#   - It is dominated by the ABSOLUTE bias of the frozen ScoreNet on
#     VAE-decoded reconstructions (domain gap).
#   - With a frozen evaluator and no real "aged" pair, the UNet can learn
#     artifacts that fool the ScoreNet toward the target number without the
#     crop actually looking older.
#
# Idea (LDLA-aligned, robust):
#   For the SAME source crop, generate two edits that share the same noise
#   and timestep but differ only in the score token:
#       - a HIGH-score prompt
#       - a LOW-score prompt
#   Then require, via a margin ranking loss, that the ScoreNet reads the
#   high-score edit as MORE aged than the low-score edit:
#
#       L_dir = relu(margin - (s_hi - s_lo)).mean()
#
#   This is RELATIVE: the absolute ScoreNet bias cancels, so it directly
#   teaches controllability ("more score token -> more aging") instead of
#   teaching the model to game an absolute number.
#
# Aging-specialist note:
#   The project intentionally biases toward AGING (not rejuvenation). The
#   ranking only enforces hi >= lo + margin; it never pushes the model to
#   rejuvenate below the source. The low branch is a relative anchor, not a
#   "make younger" target.
# ============================================================

from typing import Optional

import torch
import torch.nn as nn
import torch.nn.functional as F


def directional_score_ranking_loss(
    score_high: torch.Tensor,
    score_low: torch.Tensor,
    margin: float = 0.05,
) -> torch.Tensor:
    """
    Margin ranking loss enforcing score_high >= score_low + margin.

    Args:
        score_high: [B] predicted ScoreNet score for the high-score edit.
        score_low:  [B] predicted ScoreNet score for the low-score edit.
        margin:     desired minimum gap in normalized score units [0, 1].

    Returns:
        scalar loss.
    """
    score_high = score_high.view(-1).float()
    score_low = score_low.view(-1).float()

    gap = score_high - score_low
    loss = F.relu(float(margin) - gap)

    return loss.mean()


class DirectionalScoreLoss(nn.Module):
    """
    Thin configurable wrapper around `directional_score_ranking_loss`.

    Holds the calibration hyperparameters. The actual two edited crops are
    generated by the local loss object (which owns the UNet/VAE), then passed
    here as ScoreNet predictions.

    Hyperparameters:
        margin:
            Minimum required (high - low) gap in normalized score units.
        high_score:
            Score token value (0..1) used for the HIGH edit prompt.
        low_score:
            Score token value (0..1) used for the LOW edit prompt.
        timestep_min / timestep_max:
            Timestep window for the shared one-step / DDIM edit used by the
            directional comparison.
    """

    def __init__(
        self,
        margin: float = 0.05,
        high_score: float = 0.90,
        low_score: float = 0.30,
        timestep_min: int = 20,
        timestep_max: int = 200,
    ):
        super().__init__()
        self.margin = float(margin)
        self.high_score = float(high_score)
        self.low_score = float(low_score)
        self.timestep_min = int(timestep_min)
        self.timestep_max = int(timestep_max)

        if not (0.0 <= self.low_score < self.high_score <= 1.0):
            raise ValueError(
                "DirectionalScoreLoss requires 0 <= low_score < high_score <= 1. "
                f"Got low={self.low_score}, high={self.high_score}."
            )

    def forward(
        self,
        score_high: torch.Tensor,
        score_low: torch.Tensor,
    ) -> torch.Tensor:
        return directional_score_ranking_loss(
            score_high=score_high,
            score_low=score_low,
            margin=self.margin,
        )
